#!/bin/bash

# Command 1: Stop the gpc_start.service
sudo systemctl stop gpc_start.service

#Display Entering terminal
echo ""
echo "Entering Drifter Controller Terminal"
echo "After entering Terminal:"
echo "  Press 'q'<enter> to view commands"
echo "  Press <Ctrl - A> followed by 'x' to Exit"
echo ""

read -p "Press Enter to continue into terminal mode and turn off pump" input

# Command 2: Launch minicom
sudo minicom -o -b 57600 -D /dev/ttyS2

# Wait for user input to shut down
read -p "Press Enter to run download script"

#Run download script
sudo python3 /home/ssr/Share/driftersystem/downloadDepthLog.py

# Wait for user input to shut down
read -p "Press Enter to shutdown or <Ctrl - C> to return to OS"

# Display message before shutting down
echo "Exiting terminal and shutting down."
echo "Please replace MAGNET."

# Command 3: Shutdown the computer
sudo shutdown now
