#!/bin/bash

# Command 1: Stop the gpc_start.service
sudo systemctl stop gpc_start.service

#Display Entering terminal
echo ""
echo "Entering Drifter Controller Terminal"
echo "After entering Terminal:"
echo "  Press 'q'<enter> to view commands"
echo "  Press <Ctrl - A> followed by 'x' to Exit"
echo ""

read -p "Press Enter to continue into terminal mode and turn off pump" input

# Command 2: Launch minicom
sudo minicom -o -b 57600 -D /dev/ttyS2

# Wait for user input to shut down
read -p "Press Enter to run download script"

#Run download script
sudo python3 downloadDepthLog_rev2.py
